version: "3.8"

services:
  web:
    build:
      context: docker/nginx
    image: dlqa-web-image
    container_name: dlqa-web
    ports:
      - 8090:443
    depends_on:
      - app
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  app:
    build:
      context: docker/php
    image: dlqa-app-image
    container_name: dlqa-app
    user: appuser
    depends_on:
      - db
    volumes:
      - ./:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: "mariadb:10.8.2"
    container_name: dlqa-db
    ports:
      - 3396:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppass
    volumes:
      - dlqa-db-data:/var/lib/mysql
      - ./docker/mariadb/50-client.cnf:/etc/mysql/mariadb.conf.d/50-client.cnf
      - ./docker/mariadb/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf

networks:
  default:
    name: dlqa-network

volumes:
  dlqa-db-data:
    driver: local